[setup]
pkgs = ["php82", "php82Packages.composer", "nodejs", "php82Extensions.gd", "php82Extensions.mbstring", "php82Extensions.pdo_mysql", "php82Extensions.zip", "php82Extensions.fileinfo"]

[phases.install]
# Penting: Pastikan npm install dijalankan agar folder node_modules/ mix tercipta
cmds = [
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
    "npm install"
]

[phases.build]
# Sekarang 'mix' seharusnya sudah ada di node_modules
cmds = ["npm run prod"]
